[package]
name = "domain"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]
description = "A DNS library for Rust."
documentation = "https://docs.rs/domain/"
homepage = "https://github.com/partim/domain"
repository = "https://github.com/partim/domain"
readme = "README.md"
keywords = ["DNS", "domain", "resolver", "futures"]
license = "MIT"

[lib]
name = "domain"
path = "src/lib.rs"

[dependencies]
byteorder   = "0.5"
crossbeam   = "0.2"
rand        = "0.3"
futures     = "0.1"
tokio-core  = "0.1"
void        = "1.0"

[dev-dependencies]
argparse     = "0.2"
toml         = "0.2"
#tokio-tls    = { git = "https://github.com/tokio-rs/tokio-tls" }
